// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectEventAssos.Infrastucture.DataBase.DataContext;

#nullable disable

namespace ProjectEventAssos.Infrastucture.DataBase.Migrations
{
    [DbContext(typeof(AssocEventContext))]
    [Migration("20260410115059_SeedDataImageEvent")]
    partial class SeedDataImageEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectEventAssos.Domain.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Concert"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Conférence"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Atelier"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jazz"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Classique"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Théâtre"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Comédie"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Danse"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Cinéma"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Exposition"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Photographie"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Gastronomie"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Yoga"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Randonnée"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Jeux"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Littérature"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Musique"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bien-être"
                        });
                });

            modelBuilder.Entity("ProjectEventAssos.Domain.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<byte[]>("CoverImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateLimiteInscription")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeFinish")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MajDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<int>("MinParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Place")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("WaitList")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Events", t =>
                        {
                            t.HasCheckConstraint("CK_Event_DateFinishStart", "[DateTimeFinish] > [DateTimeStart]");

                            t.HasCheckConstraint("CK_Event_DateLimite", "[DateLimiteInscription] <= [DateTimeStart]");

                            t.HasCheckConstraint("CK_Event_MaxParticipant", "[MaxParticipants] <=200");

                            t.HasCheckConstraint("CK_Event_MinMaxParticipant", "[MinParticipants] <= [MaxParticipants]");

                            t.HasCheckConstraint("CK_Event_MinParticipant", "[MinParticipants] >= 1");
                        });
                });

            modelBuilder.Entity("ProjectEventAssos.Domain.Models.ParticipateEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ParticipateEvents");
                });

            modelBuilder.Entity("ProjectEventAssos.Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Role Admin ayant tout les droits possibles",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Role User étant le Role avec le moins de permission",
                            Name = "Utilisateur"
                        });
                });

            modelBuilder.Entity("ProjectEventAssos.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("PasswordChanged")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_User_Email_Format", "Email LIKE '%_@%_.%_'");
                        });
                });

            modelBuilder.Entity("ProjectEventAssos.Domain.Models.WaitingListEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InscriptionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("WaitingListEvents");
                });

            modelBuilder.Entity("ProjectEventAssos.Domain.Models.Event", b =>
                {
                    b.HasOne("ProjectEventAssos.Domain.Models.Categorie", "Categorie")
                        .WithMany("Events")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("ProjectEventAssos.Domain.Models.ParticipateEvent", b =>
                {
                    b.HasOne("ProjectEventAssos.Domain.Models.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectEventAssos.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectEventAssos.Domain.Models.User", b =>
                {
                    b.HasOne("ProjectEventAssos.Domain.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ProjectEventAssos.Domain.Models.WaitingListEvent", b =>
                {
                    b.HasOne("ProjectEventAssos.Domain.Models.Event", "Event")
                        .WithMany("ListWait")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectEventAssos.Domain.Models.User", "User")
                        .WithMany("WaitingListEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectEventAssos.Domain.Models.Categorie", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("ProjectEventAssos.Domain.Models.Event", b =>
                {
                    b.Navigation("ListWait");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("ProjectEventAssos.Domain.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProjectEventAssos.Domain.Models.User", b =>
                {
                    b.Navigation("WaitingListEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
